name: node Continous Integration

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs_on: ubuntu_latest
    steps:
      - uses: actions/checout@v2
      - uses: actions/setup-node@v1
        with:
          node_version: 12
      - run: npm ci
      - run: npm run build
